version: "3.5"

services:
  app:
    build: .docker/app
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app
    expose:
      - "80"
    ports:
      - "8066:80"
    networks:
      - default
networks:
  default:
    name: appnet
    driver: bridge